name: Makefile CI

on:
  push:
    branches: [ "main", "devel", "devel-olga" ]
  pull_request:
    branches: [ "main", "devel" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile code
      run: make
